### ISSUE TITLE
Vertices per tile problem

### ISSUE THREAD

**Issue by 0xmrpinheiro** [gordon-vart/opensource#2]
Hi, first of all thank you so much for this tool! It has been really helpful on my project.
I downloaded the Duke's Free Heightmaps Map 6 from the unreal engine forum, but i can't use the Vertices Per Tile on 1024. 
When i upload the tiles to unreal engine it says it cant find a 1023x1023x landscape. Any way to work around it?

**Comment by gordon-vart** [comment]
Hi there, thank you for the kind words. I believe the issue is that the heightmap you've chosen to use is really really large. I think that individual tiles cannot be that big, and therefore you need to decrease the vertices per tile down to 512 instead of 1024. This will create more sections / levels within your overall World composition, but it does work just fine and I tested it. Just lower down to 512 and regenerate all of your tiles. it will then recreate 225 separate sections within your overall world composition. good luck my friend let me know how it goes.
![Capture](https://user-images.githubusercontent.com/17886865/102019280-58ab0d00-3d38-11eb-9e4f-95a0d30fb744.PNG)
